### ISSUE TITLE
Problem running configure

### ISSUE THREAD

**Issue by sriparnaghosh** [evaleev/libint#179] opened 2020-06-17 18:42 UTC
/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/build_libint.cc:38:4: error: #error "your compiler does not provide variadic macros (but does support C++11), something is seriously broken, please create an issue at https://github.com/evaleev/libint/issues"
 #  error "your compiler does not provide variadic macros (but does support C++11), something is seriously broken, please create an issue at https://github.com/evaleev/libint/issues"
    ^~~~~
/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/build_libint.cc:2042:74: error: macro "BOOST_PP_TUPLE_TO_LIST" requires 2 arguments, but only 1 given
 BOOST_PP_LIST_FOR_EACH ( BOOST_PP_MCR1, _, BOOST_PP_TWOBODY_TASKOPER_LIST)
                                                                          ^
make[3]: *** [build_libint.o] Error 1
make[3]: *** Waiting for unfinished jobs....

-------------------

/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/strategy.cc:659:106:   required from here
/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/strategy.cc:395:41: error: no type named 'TargetType' in 'struct mpl_::arg<1>'
     typedef typename RRType::TargetType IntType;
                                         ^~~~~~~
/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/strategy.cc:397:17: error: no type named 'TargetType' in 'struct mpl_::arg<1>'
     static bool visit(const SafePtr<DirectedGraph>& dg,
                 ^~~~~
/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/strategy.cc:411:19: error: no type named 'TargetType' in 'struct mpl_::arg<1>'
       static bool _visit_cgshell(const SafePtr<DirectedGraph>& dg,
                   ^~~~~~~~~~~~~~
/software/linux-el6-x86_64/lib/libint-2.4.2/src/bin/libint/strategy.cc:424:19: error: no type named 'TargetType' in 'struct mpl_::arg<1>'
       static bool _visit_cgf(const SafePtr<DirectedGraph>& dg,
                   ^~~~~~~~~~
make[3]: *** [strategy.o] Error 1
make[3]: Leaving directory `/software/linux-el6-x86_64/lib/libint-2.4.2/build/src/bin/libint'
make[2]: *** [default] Error 1
make[2]: Leaving directory `/software/linux-el6-x86_64/lib/libint-2.4.2/build/src/bin'
make[1]: *** [default] Error 1
make[1]: Leaving directory `/software/linux-el6-x86_64/lib/libint-2.4.2/build/src'
make: *** [default] Error 1

**Comment by e-kwsm** [comment] 2020-07-09 23:23
@sriparnaghosh Are you using Boost 1.48 or earlier? (#180) The issue is possibly fixed by update of Boost.

**Closed** 2021-09-11 12:41 UTC
