### ISSUE TITLE
Build fails with GCC 10

### ISSUE THREAD

**Issue by fxcoudert** [evaleev/libint#183] opened 2020-08-01 14:15 UTC
I am trying to build libint 2.6.0 (the exact source is `libint-v2.6.0-cp2k-lmax-4.tgz` from CP2K) with GCC 10 but this fails during `make install`:

```
(cd fortran && make) || exit 1
g++-10 -E -DHAVE_CONFIG_H -D__COMPILING_LIBINT2=1 -D__COMPILING_LIBINT2=1 -I../include -I..//include  -O2 -DNDEBUG  ../include/libint2.h > ../include/libint2.h.i
python c_to_f.py ../include/libint2.h.i libint2_types_f.h Libint_t
grep '^#' ../include/libint2_types.h | grep -v '#include' > fortran_incldefs.h
FC libint_f.o
../include/libint2/util/generated/libint2_params.h:29:0:

   29 | #    if __has_include(<libint2_params.h>)
      | 
Error: missing '(' before "__has_include" operand
../include/libint2/util/generated/libint2_params.h:29:0: Error: operator "__has_include" requires a header-name
make[1]: *** [libint_f.o] Error 1
make: *** [fortran] Error 1
```

This was reported in Debian as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957443

**Comment by e-kwsm** [comment] 2020-08-02 21:44
Duplicate of #173.

**Closed** 2021-09-11 14:11 UTC
